### ISSUE TITLE
请问Hamilton问题的爬山法优化策略

### ISSUE THREAD

**Issue by hzxie** [yulingtianxia/Algorithm-Experiment#1]
师兄, 我看了你的代码, 请问为什么爬山法应该从度数少的点开始遍历呢?

**Comment by yulingtianxia** [comment]
回溯思想是动态构造一颗搜索树，并针对一些条件进行剪枝。为了加快速度，尽快找到满足条件的分支，需要从根部起尽量减少分支数量，因为这样就会减少失败后回溯的次数。根据贪心思想，肯定是从度数少的节点开始遍历咯，从小到大排列。这个可以用反证法，交换下次序计算下代价之类的来证明的。

**Comment by hzxie** [comment]
嗯~ 非常有道理。
感谢师兄~

**Comment by zjhzxhz** [comment]
嗯~ 非常有道理……

2015-10-31 18:47 GMT+08:00 杨萧玉 <notifications@github.com>:

>
> 回溯思想是动态构造一颗搜索树，并针对一些条件进行剪枝。为了加快速度，尽快找到满足条件的分支，需要从根部起尽量减少分支数量，因为这样就会减少失败后回溯的次数。根据贪心思想，肯定是从度数少的节点开始遍历咯，从小到大排列。这个可以用反证法，交换下次序计算下代价之类的来证明的。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yulingtianxia/Algorithm-Experiment/issues/1#issuecomment-152721954>
> .
>



-- 

谢浩哲
